### ISSUE TITLE
Remote Control

### ISSUE THREAD

**Issue by enlicayomer** [jitsi/jitsi-meet-electron-utils#19]
Hi, I want to test remote control but I could not activate it. What steps do I need to follow in this regard?

[usage remote control](https://github.com/jitsi/jitsi-meet-electron-utils#usage)
In which file do I need to apply the codes specified in this address?

Regards,

**Comment by serhatboyraz** [comment]
hello my friend. i dont know solution.

**Comment by ilker0** [comment]
I do not understand you

**Comment by serhatboyraz** [comment]
i saying "i dont know solution."

**Comment by ilker0** [comment]
i think you should learn js

**Comment by serhatboyraz** [comment]
i know js but i dont solution only.

**Comment by ilker0** [comment]
then who is the problem?

**Comment by bgrozev** [comment]
Please keep the discussion to the topic at hand. If you can not help, there's no need to say so explicitly.

**Comment by hristoterezov** [comment]
@enlicayomer You should call this in the render process of the window that contains the Jitsi Meet.
