### ISSUE TITLE
jitsi with jetty on ubuntu 16.04 

### ISSUE THREAD

**Issue by tkoller1** [jitsi/jitsi-meet-electron-utils#31]
For my jitsi meet on my private platform I would like to use the electron utils for changing the welcome page and eventually remote controlling jitsi. The webserver is jetty. 
Thanks for advice.
Best regards
Toni

**Comment by damencho** [comment]
You can use the jitsi-meet-electron app with your deployment.

Use the community forum for questions and problems before opening issues, thanks.
