### ISSUE TITLE
Integrate with API

### ISSUE THREAD

**Issue by premanandmanimaran** [jitsi/jitsi-meet-electron-utils#37]
Hi 
I am trying to call Jitsi Meet inside my application using Jitsi meet API. I wanted to know how i can implement Always on top , Screen Sharing and Transcribe.

Screen Sharing is working when i try in the Browser but When i try inside Electron App its not working ( it calls the screen share pop up but doesnt initialize the screen sharing.

Please help

Prem

**Comment by hristoterezov** [comment]
You need to use this repository to enable these features in the electron app. Check out https://github.com/jitsi/jitsi-meet-electron-utils#usage for more information how to use it in your project. Also you can take a look here https://github.com/jitsi/jitsi-meet-electron. I think this should be pretty close to what you want to achieve.
