### ISSUE TITLE
Question: failed to introduce the project

### ISSUE THREAD

**Issue by zhangzhoufei** [jitsi/jitsi-meet-electron-utils#59]
Error: The module '\\?\G:\ZZF\electron-vue-template-SynchronizedUpdates\node_modules\jitsi-meet-electron-utils\node_modules\robotjs\build\Release\robotjs.node'
  was compiled against a different Node.js version using
  NODE_MODULE_VERSION 72. This version of Node.js requires
  NODE_MODULE_VERSION 73. Please try re-compiling or re-installing
  the module (for instance, using `npm rebuild` or `npm install`).
      at process.func (electron/js2c/asar.js:138:31)
      at process.func [as dlopen] (electron/js2c/asar.js:138:31)
      at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
      at Object.func (electron/js2c/asar.js:138:31)
      at Object.func [as .node] (electron/js2c/asar.js:138:31)
      at Module.load (internal/modules/cjs/loader.js:645:32)
      at Function.Module._load (internal/modules/cjs/loader.js:560:12)
      at Module.require (internal/modules/cjs/loader.js:685:19)
      at require (internal/modules/cjs/helpers.js:16:16)
      at Object.<anonymous> (G:\ZZF\electron-vue-template-SynchronizedUpdates\node_modules\jitsi-meet-electron-utils\node_modules\robotjs\index.js:1:15)

**Comment by hristoterezov** [comment]
Could you please provide more details about your problem? 

How are you using jitsi-meet-electron-utils?

When do you see the error?

How are you building your project?

What operating system and environment(node, npm, node-gyp versions) are you using?

**Comment by zhangzhoufei** [comment]
> 您能否提供有关您的问题的更多详细信息？
> 
> 您如何使用jitsi-meet-electron-utils？
> 
> 什么时候看到错误？
> 
> 您如何建立项目？
> 
> 您使用什么操作系统和环境（node，npm，node-gyp版本）？
1. windwos node
2.my jitsi-meet-electron 
3. npm install   "jitsi-meet-electron-utils": "github:jitsi/jitsi-meet-electron-utils#v1.0.2", 
4. package.json
 "dependencies": {
        "jitsi-meet-electron-utils": "github:jitsi/jitsi-meet-electron-utils#v1.0.2",
5. run the my jitsi-meet-electron 
6. error：
Error: The module '\?\G:\ZZF\electron-vue-template-SynchronizedUpdates\node_modules\jitsi-meet-electron-utils\node_modules\robotjs\build\Release\robotjs.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 73. Please try re-compiling or re-installing
the module (for instance, using npm rebuild or npm install).
at process.func (electron/js2c/asar.js:138:31)
at process.func [as dlopen] (electron/js2c/asar.js:138:31)
at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
at Object.func (electron/js2c/asar.js:138:31)
at Object.func [as .node] (electron/js2c/asar.js:138:31)
at Module.load (internal/modules/cjs/loader.js:645:32)
at Function.Module._load (internal/modules/cjs/loader.js:560:12)
at Module.require (internal/modules/cjs/loader.js:685:19)
at require (internal/modules/cjs/helpers.js:16:16)
at Object. (G:\ZZF\electron-vue-template-SynchronizedUpdates\node_modules\jitsi-meet-electron-utils\node_modules\robotjs\index.js:1:15)

**Comment by zhangzhoufei** [comment]
> Could you please provide more details about your problem?
> 
> How are you using jitsi-meet-electron-utils?
> 
> When do you see the error?
> 
> How are you building your project?
> 
> What operating system and environment(node, npm, node-gyp versions) are you using?

process.versions：
node 12.4.0
electron 6.0.12
modules 73
windwos node
2.my jitsi-meet-electron
npm install "jitsi-meet-electron-utils": "github:jitsi/jitsi-meet-electron-utils#v1.0.2",
package.json
"dependencies": {
"jitsi-meet-electron-utils": "github:jitsi/jitsi-meet-electron-utils#v1.0.2",
run the my jitsi-meet-electron
error：
Error: The module '?\G:\ZZF\electron-vue-template-SynchronizedUpdates\node_modules\jitsi-meet-electron-utils\node_modules\robotjs\build\Release\robotjs.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 73. Please try re-compiling or re-installing
the module (for instance, using npm rebuild or npm install).
at process.func (electron/js2c/asar.js:138:31)
at process.func [as dlopen] (electron/js2c/asar.js:138:31)
at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
at Object.func (electron/js2c/asar.js:138:31)
at Object.func [as .node] (electron/js2c/asar.js:138:31)
at Module.load (internal/modules/cjs/loader.js:645:32)
at Function.Module._load (internal/modules/cjs/loader.js:560:12)
at Module.require (internal/modules/cjs/loader.js:685:19)
at require (internal/modules/cjs/helpers.js:16:16)
at Object. (G:\ZZF\electron-vue-template-SynchronizedUpdates\node_modules\jitsi-meet-electron-utils\node_modules\robotjs\index.js:1:15)

**Comment by hristoterezov** [comment]
Are you building jitsi-meet-electron or you are trying to use jitsi-meet-electron-utils in another project?

Again what versions of node and npm are you using?

I was definitely able to build and run the latest version from jitsi-meet-electron's master on windows with node 12!

**Comment by zhangzhoufei** [comment]
> Are you building jitsi-meet-electron or you are trying to use jitsi-meet-electron-utils in another project?
> 
> Again what versions of node and npm are you using?
> 
> I was definitely able to build and run the latest version from jitsi-meet-electron's master on windows with node 12!

process.versions：
node 12.4.0
electron 6.0.12
modules 73

**Comment by hristoterezov** [comment]
OK. So I guess we can close https://github.com/jitsi/jitsi-meet-electron/issues/185 since the problem is not related to the jitsi-meet-electron project, right?

I believe you need to rebuild jitsi-meet-electron-utils. In jitsi-meet-electron we are using electron-builder (https://github.com/electron-userland/electron-builder) for this purpose and we have the following line in package.json:
`"postinstall": "electron-builder install-app-deps",`

Let me know if this solves the problem!

**Comment by zhangzhoufei** [comment]
> 好。所以我想我们可以关闭[jitsi / jitsi-meet-electron＃185了，](https://github.com/jitsi/jitsi-meet-electron/issues/185)因为该问题与jitsi-meet-electron项目无关。
> 
> 我相信您需要重建jitsi-meet-electron-utils。为此，在jitsi-meet-electron中，我们使用电子构建器（https://github.com/electron-userland/electron-builder），在package.json中包含以下代码行：
> `"postinstall": "electron-builder install-app-deps",`
> 
> 让我知道这是否解决了问题！

**Comment by zhangzhoufei** [comment]
> OK. So I guess we can close [jitsi/jitsi-meet-electron#185](https://github.com/jitsi/jitsi-meet-electron/issues/185) since the problem is not related to the jitsi-meet-electron project, right?
> 
> I believe you need to rebuild jitsi-meet-electron-utils. In jitsi-meet-electron we are using electron-builder (https://github.com/electron-userland/electron-builder) for this purpose and we have the following line in package.json:
> `"postinstall": "electron-builder install-app-deps",`
> 
> Let me know if this solves the problem!

NO！！
 npm run postinstall
 > deasync@0.1.15 install G:\ZZF\electron-vue-template-SynchronizedUpdates\node_modules\deasync
    > node ./build.js

    `win32-x64-node-12` exists; testing
    Binary is fine; exiting

    > robotjs@0.5.1 install G:\ZZF\electron-vue-template-SynchronizedUpdates\node_modules\robotjs
    > node-gyp rebuild


    G:\ZZF\electron-vue-template-SynchronizedUpdates\node_modules\robotjs>if not defined npm_config_node_gyp (node "C:\Users\mynames\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "node C:\Users\me\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )

                    errorOut=node-pre-gyp WARN Using request for node-pre-gyp https download
    node-pre-gyp WARN Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.6/bcrypt_lib-v3.0.6-electron-v6.0-win32-x64-unknown.tar.gz
    node-pre-gyp WARN Pre-built binaries not found for bcrypt@3.0.6 and electron@6.0.12 (electron-v6.0 ABI, unknown) (falling back to source compile with node-gyp)
    internal/modules/cjs/loader.js:797
        throw err;
        ^

    Error: Cannot find module 'G:\ZZF\electron-vue-template-SynchronizedUpdates\node_modules\robotjs\node C:\Users\me\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js'
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
        at Function.Module._load (internal/modules/cjs/loader.js:687:27)
        at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
        at internal/main/run_main_module.js:17:11 {
      code: 'MODULE_NOT_FOUND',
      requireStack: []
    }
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! robotjs@0.5.1 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the robotjs@0.5.1 install script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:\Users\mynames\AppData\Roaming\npm-cache\_logs\2019-10-17T10_32_25_054Z-debug.log

                    command='C:\Program Files\nodejs\node.exe' 'C:\Users\mynames\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js' rebuild bcrypt@3.0.6 deasync@0.1.15 robotjs@0.5.1
                    workingDir=
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! names@0.0.1 postinstall: `electron-builder install-app-deps`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the names@0.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mynames\AppData\Roaming\npm-cache\_logs\2019-10-17T10_32_25_222Z-debug.log

**Comment by hristoterezov** [comment]
Hmm... It seems you have a network connection problem to download some dependancy!
