### ISSUE TITLE
powermonitor exception

### ISSUE THREAD

**Issue by tomkel** [jitsi/jitsi-meet-electron-utils#79]
I think this popped up when the brightness auto-dimmed a bit. macOS v2.0.2

![img](https://i.imgur.com/vp4WS9u.png)

**Comment by tomkel** [comment]
It also happens when my laptop resumes from sleep mode

**Comment by maddie-wang** [comment]
I get that too when I plug my laptop in to charge, and when i force quit out of the app

**Comment by lahirudx** [comment]
Same here. when trying to force close the app.

**Comment by saghul** [comment]
This is now fixe on master. A release is coming up.
