### ISSUE TITLE
Importing jitsi-meet-electron-utils in Angular 9

### ISSUE THREAD

**Issue by Rob195-ux** [jitsi/jitsi-meet-electron-utils#93]
I'm trying to import this module into Angular 9 project but i cant seem to find a clear way to do it.

What i had success with was including the node_modules JavaScript file directly in index.html of the Angular project and declaring it as a const and using it elsewhere. The problem is with this i think when the bundle / build process will happen i'm not sure if it will include it in the build.

`<script` `src="/node_modules/jitsi-meet-electron-utils/index.js"></script>`
`<script` type="text/javascript">const jitsiMeetElectronUtils = `require('jitsi-meet-electron-utils');</script>`

Can you provide insight on how to import jitsi-meet-electron-utils in Angular 9 please?

**Comment by damencho** [comment]
Please when you have questions or problems use the community forum before opening new issues.

A good example how to use it you can check https://github.com/jitsi/jitsi-meet-electron
That with the script will not work.

**Comment by Rob195-ux** [comment]
Well the thing is i did check that link before but what i was not sure was how to include it in an Angular 9 project.

Also can you please give me a link of what community forum are you talking about because i'm not sure, thanks!

**Comment by damencho** [comment]
https://community.jitsi.org
